### ISSUE TITLE
Client-side bugs tracker

### ISSUE THREAD

**Issue by soir20** [soir20/oxide#64]
**Known issues believed to be bugs in the original client**
* Inconsistent, rare crashes when teleporting to safety
* Inconsistent crashes when changing saber customization options quickly and then re-entering the inventory
* Poor performance in the saber customization menu
* Second saber blade disappears after previewing a different species

Report likely client-side bugs below to be added to the original post.

**Comment by MalikPlasmaowl** [comment]
Quitting Mine Buster while the "you missed your goal" text is visible will result in that text being stuck on screen until you restart the game.

**Comment by soir20** [comment]
Thanks @MalikPlasmaowl, I've added that to the list

**Comment by MalikPlasmaowl** [comment]
Holstered saber blades appear briefly when coming down from a jump.

**Comment by MalikPlasmaowl** [comment]
When you win a minigame on Felucia it does not play the victory music on the end screen.

**Comment by MalikPlasmaowl** [comment]
The Brezak mount does not float down slowly on other players screens

**Comment by MalikPlasmaowl** [comment]
Collecting another credit orb right after the first before the "credit earned" sound finishes will make the audio on the second orb play twice
